<?php

namespace App\Http\Middleware;

use Illuminate\Foundation\Http\Middleware\VerifyCsrfToken as Middleware;

class VerifyCsrfToken extends Middleware {

    /**
     * Indicates whether the XSRF-TOKEN cookie should be set on the response.
     *
     * @var bool
     */
    protected $addHttpCookie = true;

    /**
     * The URIs that should be excluded from CSRF verification.
     *
     * @var array
     */
    protected $except = [
        //
        'guestLogin',
        'login',
        'socialLogin',
        'autoLogin',
        'getVerificationCode',
        'freelancerSignup',
        'updateFreelancer',
        'updateUser',
        'saveFreelancerCategories',
        'saveFreelancerWeeklySchedule',
        'updateFreelancerWeeklySchedule',
        'verifyCode',
        'addBlockTime',
        'freelancerAddClass',
        'deleteClass',
        'addPromoCodes',
        'sendPromoCodes',
        'validatePromoCodes',
        'changePassword',
        'freelancerAddSession',
        'addFreelancerPricing',
        'saveFreelancerLocations',
        'updateFreelancerLocations',
        'customerSignup',
        'uploadTestFile',
        'licenceAgreement',
        'freelancerAddAppointment',
        'checkAppointment',
        'freelancerRescheduleAppointment',
        'addFreelancerReview',
        'addReviewReply',
        'processFollowing',
        'search',
        'searchClient',
        'addWalkinCustomer',
        'changeAppointmentStatus',
        'addPackage',
        'updatePackage',
        'logout',
        'updateNotificationSettings',
        'addSubscriptionSettings',
        'addPost',
        'changeClassStatus',
        'addFolder',
        'addSubscription',
        'updateClass',
        'updateFreelancerSubscriptionSettings',
        'updateNotificationStatus',
        'addPostLike',
        'addBookmark',
        'shareContent',
        'addReportPost',
        'searchFreelancers',
        'updateCustomer',
        'addProfileStories',
        'addInterests',
        'addSocialMedia',
        'addContent',
        'getFreelancerAvailableSlots',
        'updatePost',
        'deletePost',
        'getFavouriteScreenData',
        'addCreditCards',
        'processFavourite',
        'customizeHomeScreen',
        'classBooking',
        'addFeedBack',
        'getFavouriteProfilesData',
        'multipleClassBooking',
        'freelancerAddMultipleAppointment',
        'updateBankDetail',
        'prepareCheckout',
        'addStoryViews',
        'updateFolder',
        'deleteFolder',
        'deletePromoCode',
        'updateFreelancerCategory',
        'forgetPassword',
        'resetPassword',
        'deletePackage',
        'processSubscription',
        'deleteMedia',
        'hideContent',
        'authorize',
        'authorize-chat-window',
        'send-message',
        'inbox',
        'get-conversation',
        'delete-message',
        'delete-conversation',
        'handle-presence',
        'updateAppointmentDetail',
        'createAdminCustomer',
        'testExchangeRate',
        'saveCategory',
        'updateChatStatus',
        'processPaymentRequest',
        'splitOrderNotificationHook',
        'scheduler',
        'removeStory',
        'createMoyasarForm',
        'updateMoyasarForm',
        'MoyasarPaymentWebHook',
        'getsesbounce',
        'getsescomplaints',
        'PusherAndroidTokenProvider',
        'extension-callback',
        'addCaption',
        'freelancer-account-setting',
        'deleteBoat',
        'updateBoatNotificationSettings',
        'getRequestToken',
        'dummyMail',
        'capturePayment',
        'saveAuthorizationData',
        'getCardsList',
        'deleteUserCards',
        'getCodeForLogin',
    ];

}
